### ISSUE TITLE
🐛 Prod logs - column reference "id" is ambiguous

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11870]
## 🐛 Bug

I started noticing "column 'id' is ambiguous" errors in the prod logs.  It seems to have something to do witih teamables and general search and pagination total counts.

## 🕵️ Details

[2024-10-28 18:20:56] production.ERROR: SQLSTATE[42702]: Ambiguous column: 7 ERROR:  column reference "id" is ambiguous
LINE 1: ..."."teamable_type" = $10 and "id" in ($11)))))) or "id" = $12...
^ (Connection: pgsql, SQL: select count(*) as aggregate from "users" inner join "user_search_indices" on "users"."id" = "user_search_indices"."id" cross join (select websearch_to_tsquery(coalesce(english, get_current_ts_config()), Essam) AS tsquery) as "calculations" where ("user_search_indices"."searchable" @@ "calculations"."tsquery" or (("first_name"::text ilike %Essam% or "last_name"::text ilike %Essam% or "email"::text ilike %Essam%))) and (exists (select * from "pool_candidates" where "users"."id" = "pool_candidates"."user_id" and exists (select * from "pools" where "pool_candidates"."pool_id" = "pools"."id" and "submitted_at" <= 2024-10-28 18:20:56 and (exists (select * from "teams" where "pools"."id" = "teams"."teamable_id" and "teams"."teamable_type" = App\Models\Pool and "id" in (887072cc-8ffa-43cb-8839-2bdde0372932)) or exists (select * from "teams" where "pools"."team_id" = "teams"."id" and "id" in (887072cc-8ffa-43cb-8839-2bdde0372932)) or exists (select * from "communities" where "pools"."community_id" = "communities"."id" and exists (select * from "teams" where "communities"."id" = "teams"."teamable_id" and "teams"."teamable_type" = App\Models\Community and "id" in (887072cc-8ffa-43cb-8839-2bdde0372932)))))) or "id" = dcc8635d-624f-474e-86f0-dbbede64ea11) and "users"."deleted_at" is null) {"userId":"dcc8635d-624f-474e-86f0-dbbede64ea11","exception":"[object] (Illuminate\\Database\\QueryException(code: 42702): SQLSTATE[42702]: Ambiguous column: 7 ERROR:  column reference \"id\" is ambiguous
LINE 1: ...\".\"teamable_type\" = $10 and \"id\" in ($11)))))) or \"id\" = $12...
^ (Connection: pgsql, SQL: select count(*) as aggregate from \"users\" inner join \"user_search_indices\" on \"users\".\"id\" = \"user_search_indices\".\"id\" cross join (select websearch_to_tsquery(coalesce(english, get_current_ts_config()), Essam) AS tsquery) as \"calculations\" where (\"user_search_indices\".\"searchable\" @@ \"calculations\".\"tsquery\" or ((\"first_name\"::text ilike %Essam% or \"last_name\"::text ilike %Essam% or \"email\"::text ilike %Essam%))) and (exists (select * from \"pool_candidates\" where \"users\".\"id\" = \"pool_candidates\".\"user_id\" and exists (select * from \"pools\" where \"pool_candidates\".\"pool_id\" = \"pools\".\"id\" and \"submitted_at\" <= 2024-10-28 18:20:56 and (exists (select * from \"teams\" where \"pools\".\"id\" = \"teams\".\"teamable_id\" and \"teams\".\"teamable_type\" = App\\Models\\Pool and \"id\" in (887072cc-8ffa-43cb-8839-2bdde0372932)) or exists (select * from \"teams\" where \"pools\".\"team_id\" = \"teams\".\"id\" and \"id\" in (887072cc-8ffa-43cb-8839-2bdde0372932)) or exists (select * from \"communities\" where \"pools\".\"community_id\" = \"communities\".\"id\" and exists (select * from \"teams\" where \"communities\".\"id\" = \"teams\".\"teamable_id\" and \"teams\".\"teamable_type\" = App\\Models\\Community and \"id\" in (887072cc-8ffa-43cb-8839-2bdde0372932)))))) or \"id\" = dcc8635d-624f-474e-86f0-dbbede64ea11) and \"users\".\"deleted_at\" is null) at /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825)
[stacktrace]
#0 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Database/Connection.php(779): Illuminate\\Database\\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Database/Connection.php(398): Illuminate\\Database\\Connection->run('select count(*)...', Array, Object(Closure))
#2 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3130): Illuminate\\Database\\Connection->select('select count(*)...', Array, true)
#3 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3115): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3703): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3114): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3309): Illuminate\\Database\\Query\\Builder->get()
#7 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3268): Illuminate\\Database\\Query\\Builder->runPaginationCountQuery(Array)
#8 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(977): Illuminate\\Database\\Query\\Builder->getCountForPagination()
#9 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/Pagination/PaginationArgs.php(137): Illuminate\\Database\\Eloquent\\Builder->paginate(10, Array, 'page', 1)
#10 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/Pagination/PaginateDirective.php(179): Nuwave\\Lighthouse\\Pagination\\PaginationArgs->applyToBuilder(Object(Illuminate\\Database\\Eloquent\\Builder))
#11 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/Auth/CanResolvedDirective.php(40): Nuwave\\Lighthouse\\Pagination\\PaginateDirective->Nuwave\\Lighthouse\\Pagination\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Object(Nuwave\\Lighthouse\\Execution\\ResolveInfo))
#12 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/Auth/BaseCanDirective.php(91): Nuwave\\Lighthouse\\Auth\\CanResolvedDirective->authorizeRequest(NULL, Array, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Object(Nuwave\\Lighthouse\\Execution\\ResolveInfo), Object(Closure), Object(Closure))
#13 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/Auth/GuardDirective.php(56): Nuwave\\Lighthouse\\Auth\\BaseCanDirective->Nuwave\\Lighthouse\\Auth\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Object(Nuwave\\Lighthouse\\Execution\\ResolveInfo))
#14 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/Schema/Values/FieldValue.php(189): Nuwave\\Lighthouse\\Auth\\GuardDirective->Nuwave\\Lighthouse\\Auth\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Object(Nuwave\\Lighthouse\\Execution\\ResolveInfo))
#15 /home/site/wwwroot/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(737): Nuwave\\Lighthouse\\Schema\\Values\\FieldValue->Nuwave\\Lighthouse\\Schema\\Values\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#16 /home/site/wwwroot/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(653): GraphQL\\Executor\\ReferenceExecutor->resolveFieldValueOrError(Object(GraphQL\\Type\\Definition\\FieldDefinition), Object(GraphQL\\Language\\AST\\FieldNode), Object(Closure), NULL, Object(GraphQL\\Type\\Definition\\ResolveInfo), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext))
#17 /home/site/wwwroot/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1361): GraphQL\\Executor\\ReferenceExecutor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Object(ArrayObject), 'usersPaginated', Array, Array, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext))
#18 /home/site/wwwroot/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(299): GraphQL\\Executor\\ReferenceExecutor->executeFields(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Array, Array, Object(ArrayObject), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext))
#19 /home/site/wwwroot/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(237): GraphQL\\Executor\\ReferenceExecutor->executeOperation(Object(GraphQL\\Language\\AST\\OperationDefinitionNode), NULL)
#20 /home/site/wwwroot/api/vendor/webonyx/graphql-php/src/Executor/Executor.php(159): GraphQL\\Executor\\ReferenceExecutor->doExecute()
#21 /home/site/wwwroot/api/vendor/webonyx/graphql-php/src/GraphQL.php(162): GraphQL\\Executor\\Executor::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, 'UsersPaginated', NULL)
#22 /home/site/wwwroot/api/vendor/webonyx/graphql-php/src/GraphQL.php(96): GraphQL\\GraphQL::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, 'UsersPaginated', NULL, Array)
#23 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/GraphQL.php(146): GraphQL\\GraphQL::executeQuery(Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, 'UsersPaginated', NULL, Array)
#24 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/GraphQL.php(110): Nuwave\\Lighthouse\\GraphQL->executeParsedQueryRaw(Object(GraphQL\\Language\\AST\\DocumentNode), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, NULL, 'UsersPaginated', 'dc98ccd172dd6b4...')
#25 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/GraphQL.php(90): Nuwave\\Lighthouse\\GraphQL->executeParsedQuery(Object(GraphQL\\Language\\AST\\DocumentNode), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, NULL, 'UsersPaginated', 'dc98ccd172dd6b4...')
#26 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/GraphQL.php(240): Nuwave\\Lighthouse\\GraphQL->executeQueryString('query UsersPagi...', Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, NULL, 'UsersPaginated')
#27 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/GraphQL.php(203): Nuwave\\Lighthouse\\GraphQL->executeOperation(Object(GraphQL\\Server\\OperationParams), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext))
#28 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/Support/Utils.php(107): Nuwave\\Lighthouse\\GraphQL->Nuwave\\Lighthouse\\{closure}(Object(GraphQL\\Server\\OperationParams))
#29 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/GraphQL.php(201): Nuwave\\Lighthouse\\Support\\Utils::mapEach(Object(Closure), Object(GraphQL\\Server\\OperationParams))
#30 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/Http/GraphQLController.php(32): Nuwave\\Lighthouse\\GraphQL->executeOperationOrOperations(Object(GraphQL\\Server\\OperationParams), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext))
#31 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Nuwave\\Lighthouse\\Http\\GraphQLController->__invoke(Object(Illuminate\\Http\\Request), Object(Nuwave\\Lighthouse\\GraphQL), Object(Illuminate\\Events\\Dispatcher), Object(Laragraph\\Utils\\RequestParser), Object(Nuwave\\Lighthouse\\Execution\\SingleResponse), Object(Nuwave\\Lighthouse\\Execution\\ContextFactory))
#32 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Nuwave\\Lighthouse\\Http\\GraphQLController), '__invoke')
#33 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(208): Illuminate\\Routing\\Route->runController()
#34 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#35 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(161): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
#38 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(89): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter(Object(Illuminate\\Http\\Request), Object(Closure), 'graphql', Object(Closure))
#39 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'graphql')
#40 /home/site/wwwroot/api/app/Http/Middleware/AcceptLanguageMiddleware.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\AcceptLanguageMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home/site/wwwroot/api/app/Http/Middleware/SlowQueryLoggerMiddleware.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\SlowQueryLoggerMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /home/site/wwwroot/api/app/Http/Middleware/AuditQueryMiddleware.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\AuditQueryMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/Http/Middleware/AttemptAuthentication.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Nuwave\\Lighthouse\\Http\\Middleware\\AttemptAuthentication->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home/site/wwwroot/api/vendor/nuwave/lighthouse/src/Http/Middleware/AcceptJson.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Nuwave\\Lighthouse\\Http\\Middleware\\AcceptJson->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#53 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#54 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#55 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#56 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/site/wwwroot/api/app/Http/Middleware/ProtectedRequest.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ProtectedRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#75 /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#76 /home/site/wwwroot/api/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#77 {main}

## 📋 Steps to Reproduce

1. Query AppServiceConsole logs for Oct 28 between 18:20:55 and 18:20:57

## ✅ Acceptance Criteria

- [ ] Figure out how the error is being triggered
- [ ] Preven the error from ocurring

**Comment by petertgiles** [comment]
I tried but cannot reproduce this.  😢

**Comment by tristan-orourke** [comment]
Unable to reproduce, even using the exact query from logs. Into the icebox for now.

**Comment by petertgiles** [comment]
Stale.  Reopen if it reoccurs.
