### ISSUE TITLE
Jest - An update to Submit inside a test was not wrapped in act(...).

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2772]
Observed in the talentsearch jest tests:
```
  console.error
      Warning: An update to Submit inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at Submit (/home/peter/repos/gc-digital-talent/frontend/common/src/components/form/Submit/Submit.tsx:15:7)
          at SaveButton (/home/peter/repos/gc-digital-talent/frontend/talentsearch/src/js/components/applicantProfile/SaveButton.tsx:7:16)
          at div
          at ProfileFormFooter (/home/peter/repos/gc-digital-talent/frontend/talentsearch/src/js/components/applicantProfile/ProfileFormFooter.tsx:11:7)
          at form
          at Object.<anonymous>.exports.FormProvider (/home/peter/repos/gc-digital-talent/frontend/node_modules/react-hook-form/src/useFormContext.tsx:77:5)
          at div
          at div
          at section
          at ProfileFormWrapper (/home/peter/repos/gc-digital-talent/frontend/talentsearch/src/js/components/applicantProfile/ProfileFormWrapper.tsx:18:9)
          at WorkLocationPreferenceForm (/home/peter/repos/gc-digital-talent/frontend/talentsearch/src/js/components/workLocationPreferenceForm/WorkLocationPreferenceForm.tsx:37:19)
          at IntlProvider (/home/peter/repos/gc-digital-talent/frontend/node_modules/react-intl/src/components/provider.js:83:47)
          at AllTheProviders (/home/peter/repos/gc-digital-talent/frontend/talentsearch/src/js/tests/testUtils.tsx:5:40)
```

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2772?planning-poker) with ZenHub @vd1992

**Comment by petertgiles** [comment]
I was looking at this the other day.  Check out the first video on this page: https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning
