### ISSUE TITLE
Testing - SkillAccordion jest console error

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3337]
## Description
```
  console.error
    Warning: Encountered two children with the same key, `89bd9d8d-69a6-474e-8f46-7cc8796ed151`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
        at div
        at div
        at div
        at div
        at Accordion (/frontend/common/src/components/accordion/Accordion.tsx:15:8)
        at SkillAccordion (/frontend/common/src/components/UserProfile/SkillAccordion/SkillAccordion.tsx:39:8)
        at IntlProvider (/frontend/node_modules/react-intl/src/components/provider.js:84:47)
```

**Comment by mnigh** [comment]
Duplicate of #3172
